//! Application routing, written as Traefik file-provider configuration.
//!
//! ADR-0009: the router lives in a file Traefik watches, not in a Docker label
//! on the Application's container. Traefik reloads the file on its own, so
//! changing where an Application answers never touches Docker.

use std::path::{Path, PathBuf};

use crate::apps::{APP_CONTAINER_PORT, SOURCE_COMPOSE, container_name_for, project_name_for};
use crate::compose_app;
use crate::store::ApplicationRecord;

#[derive(Debug)]
pub enum RouteError {
    Write(String),
}

impl std::fmt::Display for RouteError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RouteError::Write(msg) => write!(f, "failed to write Application route: {msg}"),
        }
    }
}

impl std::error::Error for RouteError {}

/// Publishing an Application's route and taking it down again.
///
/// A trait rather than a pair of functions so the deploy path can be tested
/// without writing to the Operator's real Traefik directory.
pub trait RouteStore: Send + Sync + 'static {
    fn publish(&self, app: &ApplicationRecord) -> Result<(), RouteError>;
    fn withdraw(&self, id: &str) -> Result<(), RouteError>;
}

/// Every Hostname the Application answers on: its Hostname first, then any
/// aliases, without repeating one that appears twice.
pub fn hostnames(app: &ApplicationRecord) -> Vec<&str> {
    let mut all = vec![app.hostname.as_str()];
    for alias in &app.aliases {
        if !all.contains(&alias.as_str()) {
            all.push(alias);
        }
    }
    all
}

/// The container and port behind an Application's Hostname. A Compose
/// Application answers from its web service (ADR-0015); anything else from
/// its one container, on the default HTTP port.
pub fn backend(app: &ApplicationRecord) -> (String, u16) {
    if app.source == SOURCE_COMPOSE {
        let service = app.web_service.as_deref().unwrap_or_default();
        let container = compose_app::container_name(&project_name_for(&app.id), service);
        return (container, app.web_port.unwrap_or(APP_CONTAINER_PORT));
    }
    (
        container_name_for(&app.id),
        app.web_port.unwrap_or(APP_CONTAINER_PORT),
    )
}

/// The router is named from the id, and so is the backend it points at: both
/// survive a rename because neither is derived from the Application name.
pub fn render(app: &ApplicationRecord) -> String {
    let rule = hostnames(app)
        .iter()
        .map(|h| format!("Host(`{h}`)"))
        .collect::<Vec<_>>()
        .join(" || ");

    let id = &app.id;
    let (container, port) = backend(app);

    format!(
        r#"# Generated by self-host for Application '{name}'. Do not edit.
http:
  routers:
    app-{id}:
      rule: "{rule}"
      entryPoints:
        - websecure
      tls: {{}}
      service: app-{id}
  services:
    app-{id}:
      loadBalancer:
        servers:
          - url: "http://{container}:{port}"
"#,
        name = app.name,
        id = id,
        rule = rule,
        container = container,
        port = port,
    )
}

pub fn route_file_name(id: &str) -> String {
    format!("app-{id}.yml")
}

/// Routes as files in the directory Traefik watches.
pub struct FileRoutes {
    dir: PathBuf,
}

impl FileRoutes {
    pub fn new() -> Self {
        FileRoutes::in_dir(crate::tls::traefik_dynamic_dir())
    }

    pub fn in_dir(dir: impl Into<PathBuf>) -> Self {
        FileRoutes { dir: dir.into() }
    }

    fn path_for(&self, id: &str) -> PathBuf {
        self.dir.join(route_file_name(id))
    }
}

impl Default for FileRoutes {
    fn default() -> Self {
        FileRoutes::new()
    }
}

impl RouteStore for FileRoutes {
    fn publish(&self, app: &ApplicationRecord) -> Result<(), RouteError> {
        std::fs::create_dir_all(&self.dir)
            .map_err(|e| RouteError::Write(format!("create dynamic directory: {e}")))?;
        write_atomically(&self.path_for(&app.id), &render(app))
    }

    fn withdraw(&self, id: &str) -> Result<(), RouteError> {
        match std::fs::remove_file(self.path_for(id)) {
            Ok(()) => Ok(()),
            // Already gone is the state we wanted.
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(e) => Err(RouteError::Write(format!("remove route file: {e}"))),
        }
    }
}

/// Traefik watches the directory and reloads on every write, so a route has to
/// become visible complete or not at all — a half-written file is a parse
/// error that takes the Application off the LAN.
fn write_atomically(path: &Path, contents: &str) -> Result<(), RouteError> {
    let tmp = path.with_extension("yml.tmp");
    std::fs::write(&tmp, contents)
        .map_err(|e| RouteError::Write(format!("write {}: {e}", tmp.display())))?;
    std::fs::rename(&tmp, path)
        .map_err(|e| RouteError::Write(format!("rename into {}: {e}", path.display())))
}

/// Routes published into the embedded proxy's route table (ADR-0019).
///
/// This is the whole adapter between an Application on record and the proxy's
/// [`Publisher`](crate::proxy::Publisher): the Hostnames come off the record,
/// and the reachable address is loopback on the Host port the Web Target was
/// published on. An Application without one — deployed before the proxy moved
/// into the binary, or not yet started — publishes with no target, so the
/// proxy answers that its Application is unavailable rather than pretending
/// the Hostname does not exist.
pub struct ProxyRoutes {
    table: crate::proxy::RouteTable,
}

impl ProxyRoutes {
    pub fn new(table: crate::proxy::RouteTable) -> Self {
        ProxyRoutes { table }
    }
}

impl RouteStore for ProxyRoutes {
    fn publish(&self, app: &ApplicationRecord) -> Result<(), RouteError> {
        use crate::proxy::Publisher;

        let hostnames: Vec<String> = hostnames(app).into_iter().map(str::to_string).collect();
        let target = app
            .web_target_port
            .map(|port| std::net::SocketAddr::from(([127, 0, 0, 1], port)));
        self.table.publish(&app.id, &hostnames, target);
        Ok(())
    }

    fn withdraw(&self, id: &str) -> Result<(), RouteError> {
        use crate::proxy::Publisher;

        self.table.withdraw(id);
        Ok(())
    }
}

/// Every route store the Platform keeps, written to as one.
///
/// The Traefik files and the embedded proxy's table describe the same routes
/// in two places while both are serving, and an Application published to only
/// one of them would answer differently depending on which proxy a Consumer
/// reached. The first failure is the one reported, and the rest are still
/// written: a store that is behind is worse than a store that is behind *and*
/// was never told the rest.
pub struct AllRoutes(Vec<Box<dyn RouteStore>>);

impl AllRoutes {
    pub fn new(stores: Vec<Box<dyn RouteStore>>) -> Self {
        AllRoutes(stores)
    }
}

impl RouteStore for AllRoutes {
    fn publish(&self, app: &ApplicationRecord) -> Result<(), RouteError> {
        // Deliberately not `try_fold`: a store skipped because an earlier one
        // failed is a store that now describes a different route than the
        // rest. Every store is written, and the first failure is reported.
        let mut outcome = Ok(());
        for store in &self.0 {
            outcome = outcome.and(store.publish(app));
        }
        outcome
    }

    fn withdraw(&self, id: &str) -> Result<(), RouteError> {
        let mut outcome = Ok(());
        for store in &self.0 {
            outcome = outcome.and(store.withdraw(id));
        }
        outcome
    }
}

/// Routes kept in memory, for tests.
#[derive(Default)]
pub struct FakeRoutes {
    published: std::sync::Mutex<std::collections::HashMap<String, String>>,
}

impl FakeRoutes {
    pub fn new() -> Self {
        FakeRoutes::default()
    }

    /// The rendered route for an Application, or `None` when it has none.
    pub fn get(&self, id: &str) -> Option<String> {
        self.published.lock().unwrap().get(id).cloned()
    }

    pub fn ids(&self) -> Vec<String> {
        let mut ids: Vec<String> = self.published.lock().unwrap().keys().cloned().collect();
        ids.sort();
        ids
    }
}

impl RouteStore for FakeRoutes {
    fn publish(&self, app: &ApplicationRecord) -> Result<(), RouteError> {
        self.published
            .lock()
            .unwrap()
            .insert(app.id.clone(), render(app));
        Ok(())
    }

    fn withdraw(&self, id: &str) -> Result<(), RouteError> {
        self.published.lock().unwrap().remove(id);
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn app(id: &str, hostname: &str, aliases: &[&str]) -> ApplicationRecord {
        ApplicationRecord {
            id: id.into(),
            name: "blog".into(),
            hostname: hostname.into(),
            aliases: aliases.iter().map(|a| a.to_string()).collect(),
            image: "nginx".into(),
            status: "running".into(),
            source: "image".into(),
            last_error: None,
            compose: None,
            web_service: None,
            web_port: None,
            web_target_port: None,
        }
    }

    #[test]
    fn route_points_at_the_container_named_from_the_id() {
        let yaml = render(&app("abc123", "blog.home.lan", &[]));
        assert!(yaml.contains("app-abc123:"));
        assert!(yaml.contains("url: \"http://sf-app-abc123:80\""));
        assert!(yaml.contains("rule: \"Host(`blog.home.lan`)\""));
    }

    #[test]
    fn a_compose_application_routes_to_its_web_service() {
        let mut record = app("abc123", "hermes.home.lan", &[]);
        record.source = "compose".into();
        record.web_service = Some("hermes".into());
        record.web_port = Some(9119);
        let yaml = render(&record);
        assert!(
            yaml.contains("url: \"http://sf-app-abc123-hermes:9119\""),
            "{yaml}"
        );
    }

    #[test]
    fn aliases_join_the_rule_so_the_old_hostname_keeps_answering() {
        let yaml = render(&app("abc123", "writing.home.lan", &["blog.home.lan"]));
        assert!(yaml.contains("rule: \"Host(`writing.home.lan`) || Host(`blog.home.lan`)\""));
    }

    #[test]
    fn an_alias_repeating_the_hostname_is_not_routed_twice() {
        let record = app("abc123", "blog.home.lan", &["blog.home.lan"]);
        assert_eq!(hostnames(&record), vec!["blog.home.lan"]);
    }

    #[test]
    fn the_proxy_table_answers_every_hostname_on_the_web_targets_host_port() {
        let table = crate::proxy::RouteTable::new();
        let routes = ProxyRoutes::new(table.clone());
        let mut record = app("abc123", "writing.home.lan", &["blog.home.lan"]);
        record.web_target_port = Some(20001);

        routes.publish(&record).unwrap();

        let expected = Some(Some("127.0.0.1:20001".parse().unwrap()));
        assert_eq!(table.target_for("writing.home.lan"), expected);
        assert_eq!(table.target_for("blog.home.lan"), expected);

        routes.withdraw("abc123").unwrap();
        assert_eq!(table.target_for("writing.home.lan"), None);
    }

    #[test]
    fn an_application_with_no_web_target_port_is_published_as_unavailable() {
        let table = crate::proxy::RouteTable::new();
        let routes = ProxyRoutes::new(table.clone());

        routes
            .publish(&app("abc123", "blog.home.lan", &[]))
            .unwrap();

        // Known, and answering nowhere: a 503, not a 404 claiming there is no
        // such Application.
        assert_eq!(table.target_for("blog.home.lan"), Some(None));
    }

    #[test]
    fn every_store_is_written_even_when_an_earlier_one_fails() {
        struct Broken;
        impl RouteStore for Broken {
            fn publish(&self, _: &ApplicationRecord) -> Result<(), RouteError> {
                Err(RouteError::Write("disk is gone".into()))
            }
            fn withdraw(&self, _: &str) -> Result<(), RouteError> {
                Err(RouteError::Write("disk is gone".into()))
            }
        }

        let table = crate::proxy::RouteTable::new();
        let mut record = app("abc123", "blog.home.lan", &[]);
        record.web_target_port = Some(20001);
        let all = AllRoutes::new(vec![
            Box::new(Broken),
            Box::new(ProxyRoutes::new(table.clone())),
        ]);

        assert!(all.publish(&record).is_err());
        assert_eq!(
            table.target_for("blog.home.lan"),
            Some(Some("127.0.0.1:20001".parse().unwrap()))
        );
    }

    #[test]
    fn publishing_and_withdrawing_leaves_no_file_behind() {
        let dir = std::env::temp_dir().join(format!("self-host-routes-{}", std::process::id()));
        let routes = FileRoutes::in_dir(&dir);
        let record = app("xyz789", "blog.home.lan", &[]);

        routes.publish(&record).expect("publish");
        let path = dir.join("app-xyz789.yml");
        assert!(path.exists());
        assert!(
            std::fs::read_to_string(&path)
                .unwrap()
                .contains("sf-app-xyz789")
        );

        routes.withdraw("xyz789").expect("withdraw");
        assert!(!path.exists());
        // Withdrawing what is already gone is not an error.
        routes.withdraw("xyz789").expect("withdraw again");

        let _ = std::fs::remove_dir_all(&dir);
    }
}
